name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install EB CLI and add to PATH
        run: |
          pip install --upgrade --user awsebcli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify EB CLI
        run: |
          export PATH=$PATH:$HOME/.local/bin
          eb --version

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          export PATH=$PATH:$HOME/.local/bin
          eb init ${{ secrets.EB_APP_NAME }} --region $AWS_REGION --platform "Node.js" --interactive false
          eb use ${{ secrets.EB_ENV_NAME }}
          eb deploy
